### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by darcular** [jpap/phd-thesis-template#4]
Hi, thank you for sharing this template. I am not able to add a glossary by using this ... do you any suggestions/comments on this?

**Comment by jpap** [comment]
Hi @darcular, you would need to choose a glossary package, then create a new `\chapter` (and file) for it, and add it in there.

There's plenty of LaTeX resources for help with glossaries, [including this](https://www.overleaf.com/learn/latex/Glossaries).

Feel free to submit a pull request with your changes to the template once you get something up and running that you feel will help others.
